# Generated by Django 5.0.3 on 2024-04-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prise', models.PositiveIntegerField()),
                ('discription', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('auther', models.CharField(max_length=30)),
            ],
        ),
    ]
