# Generated by Django 5.0.3 on 2024-04-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_discription_productbook_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productbook',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='catagory',
        ),
    ]
